DROP DATABASE IF EXISTS KLEAGUE;
CREATE DATABASE KLEAGUE;
USE KLEAGUE;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    regDate DATETIME NOT NULL,
    updateDate DATETIME NOT NULL,
    loginId VARCHAR(30) NOT NULL,
    loginPw VARCHAR(50) NOT NULL,
    `name` VARCHAR(30) NOT NULL,
    nickName VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    login_type ENUM ('normal', 'kakao') DEFAULT 'normal'
);

SELECT * FROM `user`;

DROP TABLE IF EXISTS review;
CREATE TABLE review (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    regDate DATETIME NOT NULL,
    updateDate DATETIME NOT NULL,
    title VARCHAR(30) NOT NULL,
    `body` TEXT NOT NULL,
    rating FLOAT DEFAULT 0 COMMENT '별점'
);

SELECT * FROM review
ORDER BY id DESC;

DROP TABLE IF EXISTS reactionPoint;
CREATE TABLE reactionPoint (
   id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
   regDate DATETIME NOT NULL,
   updateDate DATETIME NOT NULL,
   memberId INT(10) UNSIGNED NOT NULL,
   relTypeCode CHAR(50) NOT NULL COMMENT '관련 데이터 타입 코드',
   relId INT(10) NOT NULL COMMENT '관련 데이터 번호',
   `point` INT(10) NOT NULL
);