server:
  port: 8099

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/KTrip?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    org.myproject.demo: DEBUG

kakao:
  restapi_key: 493573b251c629cab49ffc76ab14ea28
  javascript_key: 69544617df3febfc879cd18eed451ba3
  redirect_url: http://localhost:8099/login/demoshw/oauth